# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next

# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  include:
    - DRUPAL: "7"
      TK: "3.3.4"
      ID: "TK3D7"
      COMPOSER: "1"
      SITE: "reps-spain-reference"
      UPDATE: "no"
      COMMAND: "ls -lah ./vendor/ec-europa/toolkit"
    - DRUPAL: "8"
      TK: "4.4.8"
      ID: "TK4D8"
      COMPOSER: "2"
      SITE: "cnect-futurium-reference"
      UPDATE: "no"
      COMMAND: "./vendor/bin/run"
    - DRUPAL: "8"
      TK: "8.2.4"
      ID: "TK8D8"
      COMPOSER: "2"
      SITE: "cnect-futurium-reference"
      UPDATE: "yes"
      COMMAND: "./vendor/bin/run"
    - DRUPAL: "9"
      TK: "8.2.4"
      ID: "TK8D9"
      COMPOSER: "2"
      SITE: "digit-qa-reference"
      UPDATE: "no"
      COMMAND: "./vendor/bin/run"

# ==============================================================================
# Main services
# ==============================================================================
services:
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-${MYSQL_VERSION=5.7}
    command: --innodb-log-file_size=128M --max-allowed-packet=1G --innodb-buffer-pool-size=512M
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  grab-site:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-dev
    group: prepare
    commands:
      - echo PROJECT=$(pwd)
      - find . -delete
      - git init
      - git config --global --add safe.directory /test/toolkit
      - git remote add ${ID} https://github.com/jonhy81/drupal-project.git
      # - git remote add ${ID} git@github.com:ec-europa/${SITE}.git
      - git fetch ${ID}
      - git checkout -b ${DRUPAL} --track ${ID}/${DRUPAL}.x # origin/master is clone's default
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # ============================================================================
  # Prepare section:
  # ============================================================================
  set-composer:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-dev
    group: prepare
    commands:
      - composer self-update --${COMPOSER}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
  # ============================================================================
  # Setup section:
  # ============================================================================
  list-files:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-dev
    group: pre-setup
    secrets: [ github_api_token ]
    commands:
      - ls -lah
      - cat composer.json
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # ============================================================================
  # Setup section:
  # ============================================================================
  install-drupal:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-dev
    group: setup
    secrets: [ github_api_token ]
    commands:
      - COMPOSER=/test/toolkit/composer.json composer install --ansi --no-suggest --no-progress
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # ============================================================================
  # Update Toolkit
  # ============================================================================
  update-toolkit:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-dev
    group: update
    secrets: [ github_api_token ]
    commands:
      - COMPOSER=/test/toolkit/composer.json composer require --dev ec-europa/toolkit:${TK} --no-interaction
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # ============================================================================
  # Build section:
  # ============================================================================
  test-toolkit:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-dev
    group: test
    secrets: [ github_api_token ]
    commands:
      - pwd
      - ls -lah
      - ${COMMAND}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
