clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next

workspace:
  base: /test
  path: default

pipeline:
  default-message:
    image: alpine:latest
    commands:
      - echo -e "Subsite documentation pipeline."
