# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: registry.fpfis.eu/drone-plugins/git:next

# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  include:
    - PHP_VERSION: 8.1
      COMPOSER_VERSION: 2
      CUSTOM_TOOLKIT: 0
      TOOLKIT_BRANCH: 'release/8.x'
      PROJECT_ID: 'digit-subsite'
      PROJECT_VENDOR: 'digit'
      PROJECT_DESCRIPTION: 'Digit Subsite test'
      PROJECT_NAME: 'Subsite'
      PROJECT_EMAIL: 'subsite@example.com'
      PROJECT_PROFILE: 'minimal'

# ==============================================================================
# Main services
# ==============================================================================
services:
  web:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    environment: &env
      - DOCUMENT_ROOT=/test/toolkit
      - DRUPAL_DATABASE_NAME=drupal
      - DRUPAL_DATABASE_USERNAME=drone
      - DRUPAL_DATABASE_PASSWORD=password
      - DRUPAL_DATABASE_PREFIX=
      - DRUPAL_DATABASE_HOST=mysql
      - DRUPAL_DATABASE_PORT=3306
      - DRUPAL_ACCOUNT_USERNAME=admin
      - DRUPAL_ACCOUNT_PASSWORD=admin
      - DRUPAL_SPARQL_HOSTNAME=sparql
      - DRUPAL_SPARQL_PORT=8890
      - DRUPAL_BASE_URL=http://web:8080/web
      - VIRTUAL_HOST=http://web:8080/web
      - CI_COMMIT_MESSAGE=[SKIP-D9C]

  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-${MYSQL_VERSION=5.7}
    command: --innodb-log-file_size=128M --max-allowed-packet=1G --innodb-buffer-pool-size=512M
    environment:
      - MYSQL_USER=drone
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=drupal
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  sparql:
    image: registry.fpfis.eu/openeuropa/triple-store-dev:1.19.0
    environment:
      - SPARQL_UPDATE=true
      - DBA_PASSWORD=dba

  selenium:
    image: registry.fpfis.eu/fpfis/selenium:standalone-chrome-3.141.59-20210913
    shm_size: 2gb
    environment:
      - DISPLAY=:99

# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  prepare-template:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    secrets: [ github_api_token, composer_auth ]
    environment: *env
    commands:
      - find ./ -type f  ! -path '*/web/*' ! -path '*/vendor/*' ! -path '*/.git/*' ! -path '*/scripts/*' -exec sed -i 's/token_project_id/${PROJECT_ID}/g' {} +
      - find ./ -type f  ! -path '*/web/*' ! -path '*/vendor/*' ! -path '*/.git/*' ! -path '*/scripts/*' -exec sed -i 's/token_project_vendor/${PROJECT_VENDOR}/g' {} +
      - find ./ -type f  ! -path '*/web/*' ! -path '*/vendor/*' ! -path '*/.git/*' ! -path '*/scripts/*' -exec sed -i 's/token_project_description/${PROJECT_DESCRIPTION}/g' {} +
      - find ./ -type f  ! -path '*/web/*' ! -path '*/vendor/*' ! -path '*/.git/*' ! -path '*/scripts/*' -exec sed -i 's/token_project_name/${PROJECT_NAME}/g' {} +
      - find ./ -type f  ! -path '*/web/*' ! -path '*/vendor/*' ! -path '*/.git/*' ! -path '*/scripts/*' -exec sed -i 's/token_project_email/${PROJECT_EMAIL}/g' {} +
      - find ./ -type f  ! -path '*/web/*' ! -path '*/vendor/*' ! -path '*/.git/*' ! -path '*/scripts/*' -exec sed -i 's/token_project_profile/${PROJECT_PROFILE}/g' {} +
      - echo "tokens replaced"
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  install:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.3}-dev
    secrets: [ github_api_token, composer_auth, gitlab_docker_user, gitlab_docker_password ]
    commands:
      - /scripts/run.sh echo "Container ready"
      - git config --global --add safe.directory /test/toolkit
      - composer self-update --${COMPOSER_VERSION}
      - composer config -g github-oauth.github.com $${GITHUB_API_TOKEN}
      - composer install --ansi --no-progress --no-interaction
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  custom-toolkit:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    secrets: [ github_api_token, composer_auth, gitlab_docker_user, gitlab_docker_password ]
    commands:
      - /scripts/run.sh echo "Container ready"
      - rm -rf vendor/ec-europa/toolkit
      - git clone --branch ${TOOLKIT_BRANCH} https://github.com/ec-europa/toolkit.git vendor/ec-europa/toolkit
      - composer self-update --${COMPOSER_VERSION}
      - composer config -g github-oauth.github.com $${GITHUB_API_TOKEN}
      - composer install --ansi --no-progress --no-interaction
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      matrix:
        CUSTOM_TOOLKIT: 1

  install-clean:
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    secrets: [ qa_api_basic_auth, github_api_token, composer_auth, asda_user, asda_password, nextcloud_user, nextcloud_pass ]
    environment: *env
    commands:
      - /scripts/run.sh echo "Container ready"
      - ./vendor/bin/run toolkit:build-dev
      - ./vendor/bin/run toolkit:install-clean
#      - ./vendor/bin/drush sql-dump --result-file='/test/toolkit/dump.sql' --root='/test/toolkit/web'
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  toolkit-checks:
    group: qa
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    secrets: [ qa_api_basic_auth, github_api_token, composer_auth, asda_user, asda_password, nextcloud_user, nextcloud_pass ]
    environment: *env
    commands:
      - /scripts/run.sh echo "Container ready"
      - errors=0
      - ./vendor/bin/run toolkit:requirements || errors=$((errors+$?))
      - ./vendor/bin/run toolkit:component-check || errors=$((errors+$?))
      - ./vendor/bin/run toolkit:opts-review || errors=$((errors+$?))
      - echo "exit $errors"
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  toolkit-tests:
    group: qa
    image: registry.fpfis.eu/fpfis/httpd-php:${PHP_VERSION=7.4}-ci
    secrets: [ qa_api_basic_auth, github_api_token, composer_auth, asda_user, asda_password, nextcloud_user, nextcloud_pass ]
    environment: *env
    commands:
      - /scripts/run.sh echo "Container ready"
      - errors=0
      - ./vendor/bin/run toolkit:test-phpcs || errors=$((errors+$?))
      - ./vendor/bin/run toolkit:lint-php || errors=$((errors+$?))
      - ./vendor/bin/run toolkit:lint-yaml || errors=$((errors+$?))
      - ./vendor/bin/run toolkit:test-phpunit || errors=$((errors+$?))
      - ./vendor/bin/run toolkit:test-behat || errors=$((errors+$?))
      - echo "exit $errors"
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

